name: Contruccion azazel.iso
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap squashfs-tools debian-archive-keyring

      - name: Configurar y construir
        run: |
          sudo chmod -R +x config/hooks/
          sudo lb clean --all
          sudo lb config --distribution trixie \
                         --mirror-bootstrap "http://deb.debian.org/debian/" \
                         --mirror-binary "http://deb.debian.org/debian/" \
                         --archive-areas "main contrib non-free non-free-firmware" \
                         --binary-images iso-hybrid \
                         --architectures amd64 \
                         --debian-installer live
          sudo mkdir -p config/archives
          echo "deb http://deb.debian.org/debian trixie main contrib non-free non-free-firmware" | sudo tee config/archives/debian.list.chroot
          echo "deb http://deb.debian.org/debian trixie-updates main contrib non-free non-free-firmware" | sudo tee -a config/archives/debian.list.chroot
          export LB_SECURITY="false"
          sudo lb build

      - name: Subida de ISO
        uses: actions/upload-artifact@v4
        with:
          name: azazel
          path: "*.iso"