name: Contruccion azazel.iso
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias (con reintentos)
        run: |
          set -e
          for i in 1 2 3; do \
            sudo apt-get update && \
            sudo apt-get install -y live-build debootstrap squashfs-tools debian-archive-keyring && break || sleep 10; \
          done

      - name: Configurar y construir (con reintentos)
        run: |
          set -e
          sudo chmod -R +x config/hooks/
          sudo lb clean --all
          sudo lb config --distribution trixie \
                         --mirror-bootstrap "http://deb.debian.org/debian/" \
                         --mirror-binary "http://deb.debian.org/debian/" \
                         --archive-areas "main contrib non-free non-free-firmware" \
                         --binary-images iso-hybrid \
                         --architectures amd64 \
                         --debian-installer live
          export LB_SECURITY="false"
          for i in 1 2 3; do \
            sudo lb build && break || sleep 10; \
          done

      - name: Subida de ISO
        uses: actions/upload-artifact@v4
        with:
          name: azazel
          path: "*.iso"